chain:
  - name: SOLANA
    wsRpc: wss://solana-mainnet.core.chainstack.com/c0260deb07f06fce4403c9a4033adafa
    queryRpc:
      - https://dawn-spring-theorem.solana-mainnet.quiknode.pro/04e4ec0d9800a4f9246ad8c12d2dec501ef5435c
    slotParallel: 1
    txDetal: 200
    rangeRound: 200
  - name: ETH
    wsRpc: wss://mainnet.infura.io/ws/v3/your-infura-project-id
    queryRpc:
      - https://rpc.ankr.com/eth
    slotParallel: 1
    txDetal: 200
    rangeRound: 200

database:
  type: mysql
  host: 8.210.233.33
  port: 22224
  user: root
  password: HeadaXAS15x@2023!Go
  dbname: hello_sec
  sslmode: disable
  TimeZone: Asia/Shanghai

redis:
  host: 8.210.233.33
  port: 22225
  password: lasmx151asxaXA156
  db: 1

log:
  path: /Users/jclee/Desktop/hellodex

cmd:
  port: 9501
  host: localhost

http:
  port: 18080

allStart: 1